In [4]:
import pandas as pd 
leads = pd.read_csv("Leads.csv")
leads.head()

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified

In [2]:
leads.shape

(9240, 37)

In [3]:
leads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 37 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Prospect ID                                    9240 non-null   object
 1   Lead Number                                    9240 non-null   int64
 2   Lead Origin                                    9240 non-null   object
 3   Lead Source                                    9204 non-null   object
 4   Do Not Email                                   9240 non-null   object
 5   Do Not Call                                    9240 non-null   object
 6   Converted                                      9240 non-null   int64
 7   TotalVisits                                    9103 non-null   float64
 8   Total Time Spent on Website                    9240 non-null   int64
 9   Page Views Per Visit                           9103 non-null   float64
 10  Last Activity                                  9137 non-null   object
 11  Country                                        6779 non-null   object
 12  Specialization                                 7802 non-null   object
 13  How did you hear about X Education             7033 non-null   object
 14  What is your current occupation                6550 non-null   object
 15  What matters most to you in choosing a course  6531 non-null   object
 16  Search                                         9240 non-null   object
 17  Magazine                                       9240 non-null   object
 18  Newspaper Article                              9240 non-null   object
 19  X Education Forums                             9240 non-null   object
 20  Newspaper                                      9240 non-null   object
 21  Digital Advertisement                          9240 non-null   object
 22  Through Recommendations                        9240 non-null   object
 23  Receive More Updates About Our Courses         9240 non-null   object
 24  Tags                                           5887 non-null   object
 25  Lead Quality                                   4473 non-null   object
 26  Update me on Supply Chain Content              9240 non-null   object
 27  Get updates on DM Content                      9240 non-null   object
 28  Lead Profile                                   6531 non-null   object
 29  City                                           7820 non-null   object
 30  Asymmetrique Activity Index                    5022 non-null   object
 31  Asymmetrique Profile Index                     5022 non-null   object
 32  Asymmetrique Activity Score                    5022 non-null   float64
 33  Asymmetrique Profile Score                     5022 non-null   float64
 34  I agree to pay the amount through cheque       9240 non-null   object
 35  A free copy of Mastering The Interview         9240 non-null   object
 36  Last Notable Activity                          9240 non-null   object
dtypes: float64(4), int64(3), object(30)
memory usage: 2.6+ MB

In [4]:
leads.describe()

,Lead Number,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Asymmetrique Activity Score,Asymmetrique Profile Score
count,9240.000000,9240.000000,9103.000000,9240.000000,9103.000000,5022.000000,5022.000000
mean,617188.435606,0.385390,3.445238,487.698268,2.362820,14.306252,16.344883
std,23405.995698,0.486714,4.854853,548.021466,2.161418,1.386694,1.811395
min,579533.000000,0.000000,0.000000,0.000000,0.000000,7.000000,11.000000
25%,596484.500000,0.000000,1.000000,12.000000,1.000000,14.000000,15.000000
50%,615479.000000,0.000000,3.000000,248.000000,2.000000,14.000000,16.000000
75%,637387.250000,1.000000,5.000000,936.000000,3.000000,15.000000,18.000000
max,660737.000000,1.000000,251.000000,2272.000000,55.000000,18.000000,20.000000

In [5]:
leads.describe(include='object')

,Prospect ID,Lead Origin,Lead Source,Do Not Email,Do Not Call,Last Activity,Country,Specialization,How did you hear about X Education,What is your current occupation,...,Lead Quality,Update me on Supply Chain Content,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
count,9240,9240,9204,9240,9240,9137,6779,7802,7033,6550,...,4473,9240,9240,6531,7820,5022,5022,9240,9240,9240
unique,9240,5,21,2,2,17,38,19,10,6,...,5,1,1,6,7,3,3,1,2,16
top,571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,Landing Page Submission,Google,No,No,Email Opened,India,Select,Select,Unemployed,...,Might be,No,No,Select,Mumbai,02.Medium,02.Medium,No,No,Modified
freq,1,4886,2868,8506,9238,3437,6492,1942,5043,5600,...,1560,9240,9240,4146,3222,3839,2788,9240,6352,3407

In [6]:
round((leads.isnull().sum()/len(leads))*100,2)

Prospect ID                                       0.00
Lead Number                                       0.00
Lead Origin                                       0.00
Lead Source                                       0.39
Do Not Email                                      0.00
Do Not Call                                       0.00
Converted                                         0.00
TotalVisits                                       1.48
Total Time Spent on Website                       0.00
Page Views Per Visit                              1.48
Last Activity                                     1.11
Country                                          26.63
Specialization                                   15.56
How did you hear about X Education               23.89
What is your current occupation                  29.11
What matters most to you in choosing a course    29.32
Search                                            0.00
Magazine                                          0.00
Newspaper Article                                 0.00
X Education Forums                                0.00
Newspaper                                         0.00
Digital Advertisement                             0.00
Through Recommendations                           0.00
Receive More Updates About Our Courses            0.00
Tags                                             36.29
Lead Quality                                     51.59
Update me on Supply Chain Content                 0.00
Get updates on DM Content                         0.00
Lead Profile                                     29.32
City                                             15.37
Asymmetrique Activity Index                      45.65
Asymmetrique Profile Index                       45.65
Asymmetrique Activity Score                      45.65
Asymmetrique Profile Score                       45.65
I agree to pay the amount through cheque          0.00
A free copy of Mastering The Interview            0.00
Last Notable Activity                             0.00
dtype: float64

In [7]:
leads.isnull().sum()

Prospect ID                                         0
Lead Number                                         0
Lead Origin                                         0
Lead Source                                        36
Do Not Email                                        0
Do Not Call                                         0
Converted                                           0
TotalVisits                                       137
Total Time Spent on Website                         0
Page Views Per Visit                              137
Last Activity                                     103
Country                                          2461
Specialization                                   1438
How did you hear about X Education               2207
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Search                                              0
Magazine                                            0
Newspaper Article                                   0
X Education Forums                                  0
Newspaper                                           0
Digital Advertisement                               0
Through Recommendations                             0
Receive More Updates About Our Courses              0
Tags                                             3353
Lead Quality                                     4767
Update me on Supply Chain Content                   0
Get updates on DM Content                           0
Lead Profile                                     2709
City                                             1420
Asymmetrique Activity Index                      4218
Asymmetrique Profile Index                       4218
Asymmetrique Activity Score                      4218
Asymmetrique Profile Score                       4218
I agree to pay the amount through cheque            0
A free copy of Mastering The Interview              0
Last Notable Activity                               0
dtype: int64

In [8]:
(round((leads.isnull().sum()/
len(leads))*100,2)).sort_values(ascending=False)

Lead Quality                                     51.59
Asymmetrique Profile Index                       45.65
Asymmetrique Activity Score                      45.65
Asymmetrique Activity Index                      45.65
Asymmetrique Profile Score                       45.65
Tags                                             36.29
What matters most to you in choosing a course    29.32
Lead Profile                                     29.32
What is your current occupation                  29.11
Country                                          26.63
How did you hear about X Education               23.89
Specialization                                   15.56
City                                             15.37
Page Views Per Visit                              1.48
TotalVisits                                       1.48
Last Activity                                     1.11
Lead Source                                       0.39
Do Not Email                                      0.00
Lead Origin                                       0.00
Lead Number                                       0.00
Prospect ID                                       0.00
Newspaper                                         0.00
X Education Forums                                0.00
Newspaper Article                                 0.00
Magazine                                          0.00
Search                                            0.00
Total Time Spent on Website                       0.00
Do Not Call                                       0.00
Converted                                         0.00
Get updates on DM Content                         0.00
Update me on Supply Chain Content                 0.00
Through Recommendations                           0.00
Receive More Updates About Our Courses            0.00
Digital Advertisement                             0.00
I agree to pay the amount through cheque          0.00
A free copy of Mastering The Interview            0.00
Last Notable Activity                             0.00
dtype: float64

In [9]:
cols = ['Prospect ID','Lead Number']
leads = leads.drop(cols,axis=1)

In [10]:
leads.shape

(9240, 35)

In [11]:
leads.shape

(9240, 35)

In [15]:
cols_to_drop = ['Lead Quality','Asymmetrique Profile Index','Asymmetrique Activity Score','Asymmetrique Activity Index','Asymmetrique Profile Score']
leads = leads.drop(cols_to_drop, axis=1)

KeyError: "['Lead Quality', 'Asymmetrique Profile Index', 'Asymmetrique Activity Score', 'Asymmetrique Activity Index', 'Asymmetrique Profile Score'] not found in axis"

In [16]:
leads.columns

Index(['Lead Origin', 'Lead Source', 'Do Not Email', 'Do Not Call',
       'Converted', 'TotalVisits', 'Total Time Spent on Website',
       'Page Views Per Visit', 'Last Activity', 'Country', 'Specialization',
       'How did you hear about X Education', 'What is your current occupation',
       'What matters most to you in choosing a course', 'Search', 'Magazine',
       'Newspaper Article', 'X Education Forums', 'Newspaper',
       'Digital Advertisement', 'Through Recommendations',
       'Receive More Updates About Our Courses', 'Tags',
       'Update me on Supply Chain Content', 'Get updates on DM Content',
       'Lead Profile', 'City', 'I agree to pay the amount through cheque',
       'A free copy of Mastering The Interview', 'Last Notable Activity'],
      dtype='object')

In [17]:
cols_to_drop = ['Lead Quality',
                'Asymmetrique Profile Index',
                'Asymmetrique Activity Score',
                'Asymmetrique Activity Index',
                'Asymmetrique Profile Score']

leads = leads.drop(cols_to_drop, axis=1, errors='ignore')

In [18]:
leads.shape

(9240, 30)

In [19]:
round((leads.isnull().sum()/
len(leads))*100,2).sort_values(ascending=False)

Tags                                             36.29
What matters most to you in choosing a course    29.32
Lead Profile                                     29.32
What is your current occupation                  29.11
Country                                          26.63
How did you hear about X Education               23.89
Specialization                                   15.56
City                                             15.37
Page Views Per Visit                              1.48
TotalVisits                                       1.48
Last Activity                                     1.11
Lead Source                                       0.39
Converted                                         0.00
Lead Origin                                       0.00
Total Time Spent on Website                       0.00
Do Not Email                                      0.00
Do Not Call                                       0.00
Search                                            0.00
Newspaper                                         0.00
Magazine                                          0.00
Newspaper Article                                 0.00
X Education Forums                                0.00
Receive More Updates About Our Courses            0.00
Through Recommendations                           0.00
Digital Advertisement                             0.00
Update me on Supply Chain Content                 0.00
Get updates on DM Content                         0.00
I agree to pay the amount through cheque          0.00
A free copy of Mastering The Interview            0.00
Last Notable Activity                             0.00
dtype: float64

In [21]:
leads = leads[~pd.isnull(leads['Lead Profile'])]

In [22]:
leads.shape

(6531, 30)

In [23]:
round((leads.isnull().sum()/
len(leads))*100,2).sort_values(ascending=False)

Country                                          24.58
Tags                                             11.10
Page Views Per Visit                              1.99
TotalVisits                                       1.99
Last Activity                                     1.58
Lead Source                                       0.55
Converted                                         0.00
Do Not Call                                       0.00
Do Not Email                                      0.00
Total Time Spent on Website                       0.00
Specialization                                    0.00
How did you hear about X Education                0.00
What is your current occupation                   0.00
Lead Origin                                       0.00
What matters most to you in choosing a course     0.00
Search                                            0.00
Newspaper Article                                 0.00
Magazine                                          0.00
Newspaper                                         0.00
Digital Advertisement                             0.00
Through Recommendations                           0.00
X Education Forums                                0.00
Receive More Updates About Our Courses            0.00
Update me on Supply Chain Content                 0.00
Get updates on DM Content                         0.00
Lead Profile                                      0.00
City                                              0.00
I agree to pay the amount through cheque          0.00
A free copy of Mastering The Interview            0.00
Last Notable Activity                             0.00
dtype: float64

In [24]:
leads = leads[~pd.isnull(leads['Country'])]

In [25]:
leads.shape

(4926, 30)

In [27]:
round((leads.isnull().sum()/len(leads))*100,2).sort_values(ascending=False)

Tags                                             7.94
Lead Source                                      0.02
Do Not Email                                     0.00
Do Not Call                                      0.00
Converted                                        0.00
Lead Origin                                      0.00
Total Time Spent on Website                      0.00
Page Views Per Visit                             0.00
Last Activity                                    0.00
Country                                          0.00
Specialization                                   0.00
How did you hear about X Education               0.00
What is your current occupation                  0.00
TotalVisits                                      0.00
What matters most to you in choosing a course    0.00
Search                                           0.00
Newspaper Article                                0.00
Magazine                                         0.00
Newspaper                                        0.00
Digital Advertisement                            0.00
Through Recommendations                          0.00
X Education Forums                               0.00
Receive More Updates About Our Courses           0.00
Update me on Supply Chain Content                0.00
Get updates on DM Content                        0.00
Lead Profile                                     0.00
City                                             0.00
I agree to pay the amount through cheque         0.00
A free copy of Mastering The Interview           0.00
Last Notable Activity                            0.00
dtype: float64

In [28]:
leads = leads[~pd.isnull(leads['Tags'])]

In [29]:
leads.shape

(4535, 30)

In [30]:
round((leads.isnull().sum()/len(leads))*100,2).sort_values(ascending=False)

Lead Source                                      0.02
Lead Origin                                      0.00
Do Not Email                                     0.00
Do Not Call                                      0.00
Converted                                        0.00
TotalVisits                                      0.00
Total Time Spent on Website                      0.00
Page Views Per Visit                             0.00
Last Activity                                    0.00
Country                                          0.00
Specialization                                   0.00
How did you hear about X Education               0.00
What is your current occupation                  0.00
What matters most to you in choosing a course    0.00
Search                                           0.00
Magazine                                         0.00
Newspaper Article                                0.00
X Education Forums                               0.00
Newspaper                                        0.00
Digital Advertisement                            0.00
Through Recommendations                          0.00
Receive More Updates About Our Courses           0.00
Tags                                             0.00
Update me on Supply Chain Content                0.00
Get updates on DM Content                        0.00
Lead Profile                                     0.00
City                                             0.00
I agree to pay the amount through cheque         0.00
A free copy of Mastering The Interview           0.00
Last Notable Activity                            0.00
dtype: float64

In [31]:
leads.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4535 entries, 1 to 9239
Data columns (total 30 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Lead Origin                                    4535 non-null   object
 1   Lead Source                                    4534 non-null   object
 2   Do Not Email                                   4535 non-null   object
 3   Do Not Call                                    4535 non-null   object
 4   Converted                                      4535 non-null   int64
 5   TotalVisits                                    4535 non-null   float64
 6   Total Time Spent on Website                    4535 non-null   int64
 7   Page Views Per Visit                           4535 non-null   float64
 8   Last Activity                                  4535 non-null   object
 9   Country                                        4535 non-null   object
 10  Specialization                                 4535 non-null   object
 11  How did you hear about X Education             4535 non-null   object
 12  What is your current occupation                4535 non-null   object
 13  What matters most to you in choosing a course  4535 non-null   object
 14  Search                                         4535 non-null   object
 15  Magazine                                       4535 non-null   object
 16  Newspaper Article                              4535 non-null   object
 17  X Education Forums                             4535 non-null   object
 18  Newspaper                                      4535 non-null   object
 19  Digital Advertisement                          4535 non-null   object
 20  Through Recommendations                        4535 non-null   object
 21  Receive More Updates About Our Courses         4535 non-null   object
 22  Tags                                           4535 non-null   object
 23  Update me on Supply Chain Content              4535 non-null   object
 24  Get updates on DM Content                      4535 non-null   object
 25  Lead Profile                                   4535 non-null   object
 26  City                                           4535 non-null   object
 27  I agree to pay the amount through cheque       4535 non-null   object
 28  A free copy of Mastering The Interview         4535 non-null   object
 29  Last Notable Activity                          4535 non-null   object
dtypes: float64(2), int64(2), object(26)
memory usage: 1.1+ MB

In [32]:
varlist = ['Do Not Email','Do Not Call','Search','Magazine','Newspaper Article',
           'X Education Forums','Newspaper','Digital Advertisement',
           'Through Recommendations','Receive More Updates About Our Courses',
           'Update me on Supply Chain Content','Get updates on DM Content',
           'I agree to pay the amount through cheque',
           'A free copy of Mastering The Interview']

def binary_map(x):
    return x.map({'Yes':1,'No':0})

leads[varlist] = leads[varlist].apply(binary_map)

In [33]:
leads.head()

,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Country,...,Through Recommendations,Receive More Updates About Our Courses,Tags,Update me on Supply Chain Content,Get updates on DM Content,Lead Profile,City,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
1,API,Organic Search,0,0,0,5.0,674,2.5,Email Opened,India,...,0,0,Ringing,0,0,Select,Select,0,0,Email Opened
2,Landing Page Submission,Direct Traffic,0,0,1,2.0,1532,2.0,Email Opened,India,...,0,0,Will revert after reading the email,0,0,Potential Lead,Mumbai,0,1,Email Opened
3,Landing Page Submission,Direct Traffic,0,0,0,1.0,305,1.0,Unreachable,India,...,0,0,Ringing,0,0,Select,Mumbai,0,0,Modified
4,Landing Page Submission,Google,0,0,1,2.0,1428,1.0,Converted to Lead,India,...,0,0,Will revert after reading the email,0,0,Select,Mumbai,0,0,Modified
6,Landing Page Submission,Google,0,0,1,2.0,1640,2.0,Email Opened,India,...,0,0,Will revert after reading the email,0,0,Potential Lead,Mumbai,0,0,Modified

In [34]:
dummy = pd.get_dummies(leads[['Lead Origin','Lead Source']], drop_first=True)

In [35]:
dummy.head()

,Lead Origin_Landing Page Submission,Lead Origin_Lead Add Form,Lead Source_Facebook,Lead Source_Google,Lead Source_Olark Chat,Lead Source_Organic Search,Lead Source_Pay per Click Ads,Lead Source_Press_Release,Lead Source_Reference,Lead Source_Referral Sites,Lead Source_Social Media,Lead Source_WeLearn,Lead Source_Welingak Website,Lead Source_bing,Lead Source_testone
1,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False
6,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False

In [37]:
leads = pd.concat([leads, dummy], axis=1)

In [38]:
leads.drop(['Lead Origin','Lead Source'], axis=1, inplace=True)

In [39]:
leads.head()

,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Country,Specialization,How did you hear about X Education,...,Lead Source_Organic Search,Lead Source_Pay per Click Ads,Lead Source_Press_Release,Lead Source_Reference,Lead Source_Referral Sites,Lead Source_Social Media,Lead Source_WeLearn,Lead Source_Welingak Website,Lead Source_bing,Lead Source_testone
1,0,0,0,5.0,674,2.5,Email Opened,India,Select,Select,...,True,False,False,False,False,False,False,False,False,False
2,0,0,1,2.0,1532,2.0,Email Opened,India,Business Administration,Select,...,False,False,False,False,False,False,False,False,False,False
3,0,0,0,1.0,305,1.0,Unreachable,India,Media and Advertising,Word Of Mouth,...,False,False,False,False,False,False,False,False,False,False
4,0,0,1,2.0,1428,1.0,Converted to Lead,India,Select,Other,...,False,False,False,False,False,False,False,False,False,False
6,0,0,1,2.0,1640,2.0,Email Opened,India,Supply Chain Management,Online Search,...,False,False,False,False,False,False,False,False,False,False

In [40]:
varlist = ['Specialization','What is your current occupation','What matters most to you in choosing a course']

In [41]:
dummy = pd.get_dummies(leads[varlist], drop_first=True)

In [42]:
leads = pd.concat([leads, dummy], axis=1)

In [43]:
leads.drop(varlist, axis=1, inplace=True)

In [44]:
leads.head()

,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Country,How did you hear about X Education,Search,...,Specialization_Select,Specialization_Services Excellence,Specialization_Supply Chain Management,Specialization_Travel and Tourism,What is your current occupation_Housewife,What is your current occupation_Other,What is your current occupation_Student,What is your current occupation_Unemployed,What is your current occupation_Working Professional,What matters most to you in choosing a course_Other
1,0,0,0,5.0,674,2.5,Email Opened,India,Select,0,...,True,False,False,False,False,False,False,True,False,False
2,0,0,1,2.0,1532,2.0,Email Opened,India,Select,0,...,False,False,False,False,False,False,True,False,False,False
3,0,0,0,1.0,305,1.0,Unreachable,India,Word Of Mouth,0,...,False,False,False,False,False,False,False,True,False,False
4,0,0,1,2.0,1428,1.0,Converted to Lead,India,Other,0,...,True,False,False,False,False,False,False,True,False,False
6,0,0,1,2.0,1640,2.0,Email Opened,India,Online Search,0,...,False,False,True,False,False,False,False,True,False,False

In [45]:
leads.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4535 entries, 1 to 9239
Data columns (total 64 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Do Not Email                                          4535 non-null   int64
 1   Do Not Call                                           4535 non-null   int64
 2   Converted                                             4535 non-null   int64
 3   TotalVisits                                           4535 non-null   float64
 4   Total Time Spent on Website                           4535 non-null   int64
 5   Page Views Per Visit                                  4535 non-null   float64
 6   Last Activity                                         4535 non-null   object
 7   Country                                               4535 non-null   object
 8   How did you hear about X Education                    4535 non-null   object
 9   Search                                                4535 non-null   int64
 10  Magazine                                              4535 non-null   int64
 11  Newspaper Article                                     4535 non-null   int64
 12  X Education Forums                                    4535 non-null   int64
 13  Newspaper                                             4535 non-null   int64
 14  Digital Advertisement                                 4535 non-null   int64
 15  Through Recommendations                               4535 non-null   int64
 16  Receive More Updates About Our Courses                4535 non-null   int64
 17  Tags                                                  4535 non-null   object
 18  Update me on Supply Chain Content                     4535 non-null   int64
 19  Get updates on DM Content                             4535 non-null   int64
 20  Lead Profile                                          4535 non-null   object
 21  City                                                  4535 non-null   object
 22  I agree to pay the amount through cheque              4535 non-null   int64
 23  A free copy of Mastering The Interview                4535 non-null   int64
 24  Last Notable Activity                                 4535 non-null   object
 25  Lead Origin_Landing Page Submission                   4535 non-null   bool
 26  Lead Origin_Lead Add Form                             4535 non-null   bool
 27  Lead Source_Facebook                                  4535 non-null   bool
 28  Lead Source_Google                                    4535 non-null   bool
 29  Lead Source_Olark Chat                                4535 non-null   bool
 30  Lead Source_Organic Search                            4535 non-null   bool
 31  Lead Source_Pay per Click Ads                         4535 non-null   bool
 32  Lead Source_Press_Release                             4535 non-null   bool
 33  Lead Source_Reference                                 4535 non-null   bool
 34  Lead Source_Referral Sites                            4535 non-null   bool
 35  Lead Source_Social Media                              4535 non-null   bool
 36  Lead Source_WeLearn                                   4535 non-null   bool
 37  Lead Source_Welingak Website                          4535 non-null   bool
 38  Lead Source_bing                                      4535 non-null   bool
 39  Lead Source_testone                                   4535 non-null   bool
 40  Specialization_Business Administration                4535 non-null   bool
 41  Specialization_E-Business                             4535 non-null   bool
 42  Specialization_E-COMMERCE                             4535 non-null   bool
 43  Specialization_Finance Management                     4535 non-null   bool
 44  Specialization_Healthcare Management                  4535 non-null   bool
 45  Specialization_Hospitality Management                 4535 non-null   bool
 46  Specialization_Human Resource Management              4535 non-null   bool
 47  Specialization_IT Projects Management                 4535 non-null   bool
 48  Specialization_International Business                 4535 non-null   bool
 49  Specialization_Marketing Management                   4535 non-null   bool
 50  Specialization_Media and Advertising                  4535 non-null   bool
 51  Specialization_Operations Management                  4535 non-null   bool
 52  Specialization_Retail Management                      4535 non-null   bool
 53  Specialization_Rural and Agribusiness                 4535 non-null   bool
 54  Specialization_Select                                 4535 non-null   bool
 55  Specialization_Services Excellence                    4535 non-null   bool
 56  Specialization_Supply Chain Management                4535 non-null   bool
 57  Specialization_Travel and Tourism                     4535 non-null   bool
 58  What is your current occupation_Housewife             4535 non-null   bool
 59  What is your current occupation_Other                 4535 non-null   bool
 60  What is your current occupation_Student               4535 non-null   bool
 61  What is your current occupation_Unemployed            4535 non-null   bool
 62  What is your current occupation_Working Professional  4535 non-null   bool
 63  What matters most to you in choosing a course_Other   4535 non-null   bool
dtypes: bool(39), float64(2), int64(16), object(7)
memory usage: 1.1+ MB

In [46]:
varlist = ['Last Activity','Country','Lead Profile']

In [47]:
dummy = pd.get_dummies(leads[varlist], drop_first=True)

In [48]:
leads = pd.concat([leads, dummy], axis=1)

In [49]:
leads.drop(varlist, axis=1, inplace=True)

In [50]:
leads.head()

,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,How did you hear about X Education,Search,Magazine,Newspaper Article,...,Country_Uganda,Country_United Arab Emirates,Country_United Kingdom,Country_United States,Country_Vietnam,Lead Profile_Lateral Student,Lead Profile_Other Leads,Lead Profile_Potential Lead,Lead Profile_Select,Lead Profile_Student of SomeSchool
1,0,0,0,5.0,674,2.5,Select,0,0,0,...,False,False,False,False,False,False,False,False,True,False
2,0,0,1,2.0,1532,2.0,Select,0,0,0,...,False,False,False,False,False,False,False,True,False,False
3,0,0,0,1.0,305,1.0,Word Of Mouth,0,0,0,...,False,False,False,False,False,False,False,False,True,False
4,0,0,1,2.0,1428,1.0,Other,0,0,0,...,False,False,False,False,False,False,False,False,True,False
6,0,0,1,2.0,1640,2.0,Online Search,0,0,0,...,False,False,False,False,False,False,False,True,False,False

In [51]:
leads.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4535 entries, 1 to 9239
Columns: 112 entries, Do Not Email to Lead Profile_Student of SomeSchool
dtypes: bool(90), float64(2), int64(16), object(4)
memory usage: 1.2+ MB

In [52]:
leads.select_dtypes(include=['object']).columns

Index(['How did you hear about X Education', 'Tags', 'City',
       'Last Notable Activity'],
      dtype='object')

In [53]:
varlist = ['How did you hear about X Education',
           'Tags',
           'City',
           'Last Notable Activity']

In [54]:
dummy = pd.get_dummies(leads[varlist], drop_first=True)

In [55]:
leads = pd.concat([leads, dummy], axis=1)

In [56]:
leads.drop(varlist, axis=1, inplace=True)

In [57]:
leads.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4535 entries, 1 to 9239
Columns: 161 entries, Do Not Email to Last Notable Activity_View in browser link Clicked
dtypes: bool(143), float64(2), int64(16)
memory usage: 1.3 MB

In [58]:
leads.select_dtypes(include=['object']).columns

Index([], dtype='object')

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X = leads.drop('Converted', axis=1)
y = leads['Converted']

In [61]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=100
)

In [62]:
from sklearn.preprocessing import StandardScaler

In [63]:
scaler = StandardScaler()

In [65]:
X_train[['TotalVisits','Total Time Spent on Website','Page Views Per Visit']] = scaler.fit_transform(
    X_train[['TotalVisits','Total Time Spent on Website','Page Views Per Visit']]
)

In [66]:
import statsmodels.api as sm

In [67]:
logm1 = sm.GLM(y_train, sm.add_constant(X_train), family=sm.families.Binomial())

ValueError: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).

In [68]:
X_train = X_train.astype(int)

In [69]:
logm1 = sm.GLM(y_train, sm.add_constant(X_train), family=sm.families.Binomial())

In [70]:
res = logm1.fit()

In [71]:
res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:              Converted   No. Observations:                 3174
Model:                            GLM   Df Residuals:                     3036
Model Family:                Binomial   Df Model:                          137
Link Function:                  Logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -357.63
Date:                Sat, 23 May 2026   Deviance:                       715.27
Time:                        11:46:37   Pearson chi2:                 2.57e+03
No. Iterations:                    28   Pseudo R-squ. (CS):             0.6799
Covariance Type:            nonrobust
============================================================================================================================
                                                               coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------------
const                                                       46.3902   1.89e+06   2.46e-05      1.000    -3.7e+06     3.7e+06
Do Not Email                                                -0.5955      0.614     -0.969      0.332      -1.800       0.609
Do Not Call                                                 24.9962   3.54e+05   7.06e-05      1.000   -6.94e+05    6.94e+05
TotalVisits                                                  0.2398      0.115      2.078      0.038       0.014       0.466
Total Time Spent on Website                                  1.3167      0.181      7.267      0.000       0.962       1.672
Page Views Per Visit                                        -0.1959      0.169     -1.162      0.245      -0.526       0.135
Search                                                      -0.9119      3.394     -0.269      0.788      -7.565       5.741
Magazine                                                  6.621e-08      0.072   9.19e-07      1.000      -0.141       0.141
Newspaper Article                                           18.7892   1.17e+04      0.002      0.999    -2.3e+04     2.3e+04
X Education Forums                                       -1.043e-07      0.097  -1.07e-06      1.000      -0.191       0.191
Newspaper                                                -1.609e-07      0.185   -8.7e-07      1.000      -0.363       0.363
Digital Advertisement                                      -31.0765   3.28e+07  -9.47e-07      1.000   -6.43e+07    6.43e+07
Through Recommendations                                     25.7480   9.71e+05   2.65e-05      1.000    -1.9e+06     1.9e+06
Receive More Updates About Our Courses                     8.49e-08      0.088   9.62e-07      1.000      -0.173       0.173
Update me on Supply Chain Content                         3.624e-07      0.378   9.59e-07      1.000      -0.740       0.740
Get updates on DM Content                                -2.104e-07      0.195  -1.08e-06      1.000      -0.381       0.381
I agree to pay the amount through cheque                 -1.731e-07      0.181  -9.58e-07      1.000      -0.354       0.354
A free copy of Mastering The Interview                       0.0113      0.373      0.030      0.976      -0.720       0.743
Lead Origin_Landing Page Submission                          0.2818      0.471      0.599      0.549      -0.641       1.205
Lead Origin_Lead Add Form                                   18.7974   1.27e+06   1.48e-05      1.000   -2.49e+06    2.49e+06
Lead Source_Facebook                                     -1.388e-07      0.152  -9.15e-07      1.000      -0.297       0.297
Lead Source_Google                                           0.1836      0.348      0.527      0.598      -0.499       0.866
Lead Source_Olark Chat                                       0.8559      1.231      0.695      0.487      -1.558       3.270
Lead Source_Organic Search                                   0.3927      0.345      1.138      0.255      -0.283       1.069
Lead Source_Pay per Click Ads                              -25.8259    1.9e+06  -1.36e-05      1.000   -3.72e+06    3.72e+06
Lead Source_Press_Release                                -3.465e-07      0.329  -1.05e-06      1.000      -0.645       0.645
Lead Source_Reference                                        7.4773    1.3e+06   5.76e-06      1.000   -2.55e+06    2.55e+06
Lead Source_Referral Sites                                   1.5303      0.903      1.695      0.090      -0.239       3.300
Lead Source_Social Media                                     1.9779      7.157      0.276      0.782     -12.051      16.006
Lead Source_WeLearn                                      -8.769e-08      0.095  -9.27e-07      1.000      -0.185       0.185
Lead Source_Welingak Website                                11.3201   2.53e+06   4.48e-06      1.000   -4.95e+06    4.95e+06
Lead Source_bing                                           -24.0738   3.03e+06  -7.96e-06      1.000   -5.93e+06    5.93e+06
Lead Source_testone                                      -1.784e-07      0.208   -8.6e-07      1.000      -0.407       0.407
Specialization_Business Administration                      -0.2599      0.649     -0.401      0.689      -1.531       1.012
Specialization_E-Business                                   -1.5243      1.191     -1.280      0.201      -3.859       0.810
Specialization_E-COMMERCE                                   -0.0514      0.938     -0.055      0.956      -1.889       1.787
Specialization_Finance Management                           -0.7495      0.568     -1.320      0.187      -1.862       0.363
Specialization_Healthcare Management                         1.2822      0.928      1.381      0.167      -0.537       3.102
Specialization_Hospitality Management                       -1.4648      0.855     -1.713      0.087      -3.140       0.211
Specialization_Human Resource Management                    -0.5725      0.576     -0.994      0.320      -1.701       0.556
Specialization_IT Projects Management                       -0.0848      0.677     -0.125      0.900      -1.413       1.243
Specialization_International Business                       -0.3133      0.801     -0.391      0.696      -1.882       1.256
Specialization_Marketing Management                         -0.2542      0.568     -0.447      0.655      -1.368       0.860
Specialization_Media and Advertising                        -0.5408      0.811     -0.667      0.505      -2.131       1.049
Specialization_Operations Management                        -0.0728      0.615     -0.118      0.906      -1.279       1.133
Specialization_Retail Management                            -0.5187      1.053     -0.493      0.622      -2.583       1.545
Specialization_Rural and Agribusiness                        0.7429      1.014      0.733      0.464      -1.244       2.730
Specialization_Select                                       -0.5798      0.725     -0.800      0.424      -2.000       0.841
Specialization_Services Excellence                          -0.8714      1.327     -0.657      0.511      -3.471       1.729
Specialization_Supply Chain Management                      -1.4211      0.662     -2.148      0.032      -2.718      -0.125
Specialization_Travel and Tourism                           -1.0810      0.787     -1.374      0.169      -2.623       0.461
What is your current occupation_Housewife                   24.4379   7.87e+05   3.11e-05      1.000   -1.54e+06    1.54e+06
What is your current occupation_Other                       -0.1889      5.816     -0.032      0.974     -11.589      11.211
What is your current occupation_Student                      0.6768      5.683      0.119      0.905     -10.463      11.816
What is your current occupation_Unemployed                  -0.3700      5.607     -0.066      0.947     -11.359      10.619
What is your current occupation_Working Professional         0.2377      5.620      0.042      0.966     -10.776      11.252
What matters most to you in choosing a course_Other        -23.8737   7.94e+05  -3.01e-05      1.000   -1.56e+06    1.56e+06
Last Activity_Converted to Lead                            -24.3811   1.01e+06  -2.42e-05      1.000   -1.97e+06    1.97e+06
Last Activity_Email Bounced                                -26.4588   1.01e+06  -2.63e-05      1.000   -1.97e+06    1.97e+06
Last Activity_Email Link Clicked                           -23.0099   1.01e+06  -2.29e-05      1.000   -1.97e+06    1.97e+06
Last Activity_Email Marked Spam                             -2.4796      1e+06  -2.48e-06      1.000   -1.96e+06    1.96e+06
Last Activity_Email Opened                                 -24.3634   1.01e+06  -2.42e-05      1.000   -1.97e+06    1.97e+06
Last Activity_Email Received                                -1.1073   9.71e+05  -1.14e-06      1.000    -1.9e+06     1.9e+06
Last Activity_Form Submitted on Website                    -23.4961   1.01e+06  -2.33e-05      1.000   -1.97e+06    1.97e+06
Last Activity_Had a Phone Conversation                     -25.5999   1.01e+06  -2.54e-05      1.000   -1.97e+06    1.97e+06
Last Activity_Olark Chat Conversation                      -23.0186   1.01e+06  -2.29e-05      1.000   -1.97e+06    1.97e+06
Last Activity_Page Visited on Website                      -24.1759   1.01e+06   -2.4e-05      1.000   -1.97e+06    1.97e+06
Last Activity_SMS Sent                                     -22.4259   1.01e+06  -2.23e-05      1.000   -1.97e+06    1.97e+06
Last Activity_Unreachable                                  -23.8252   1.01e+06  -2.37e-05      1.000   -1.97e+06    1.97e+06
Last Activity_Unsubscribed                                 -23.6677   1.01e+06  -2.35e-05      1.000   -1.97e+06    1.97e+06
Last Activity_View in browser link Clicked                 -23.0854   1.08e+06  -2.14e-05      1.000   -2.11e+06    2.11e+06
Last Activity_Visited Booth in Tradeshow                 -1.581e-08      0.021  -7.48e-07      1.000      -0.041       0.041
Country_Bahrain                                              1.6923      7.548      0.224      0.823     -13.101      16.486
Country_Bangladesh                                          27.5725   3.52e+06   7.83e-06      1.000    -6.9e+06     6.9e+06
Country_Canada                                             -23.1016   5.72e+05  -4.04e-05      1.000   -1.12e+06    1.12e+06
Country_China                                            -2.088e-09      0.007   -2.9e-07      1.000      -0.014       0.014
Country_Denmark                                           3.064e-09      0.003   1.22e-06      1.000      -0.005       0.005
Country_France                                              23.2646   4.16e+05    5.6e-05      1.000   -8.15e+05    8.15e+05
Country_Germany                                              7.0599      4.690      1.505      0.132      -2.132      16.252
Country_Ghana                                              -21.2300    1.3e+06  -1.63e-05      1.000   -2.55e+06    2.55e+06
Country_Hong Kong                                            5.0752      4.649      1.092      0.275      -4.036      14.186
Country_India                                                0.9016      4.370      0.206      0.837      -7.663       9.466
Country_Indonesia                                         2.954e-08      0.028   1.04e-06      1.000      -0.056       0.056
Country_Italy                                            -1.989e-08      0.035  -5.72e-07      1.000      -0.068       0.068
Country_Kenya                                             6.232e-09      0.008   7.62e-07      1.000      -0.016       0.016
Country_Kuwait                                             -21.9636   7.67e+05  -2.86e-05      1.000    -1.5e+06     1.5e+06
Country_Malaysia                                          4.297e-08      0.034   1.26e-06      1.000      -0.067       0.067
Country_Netherlands                                        -26.3165    1.3e+06  -2.02e-05      1.000   -2.55e+06    2.55e+06
Country_Nigeria                                            -22.8891    8.7e+05  -2.63e-05      1.000   -1.71e+06    1.71e+06
Country_Oman                                                 2.0830      5.752      0.362      0.717      -9.192      13.358
Country_Philippines                                        -23.2574    1.3e+06  -1.79e-05      1.000   -2.55e+06    2.55e+06
Country_Qatar                                                2.1536      4.997      0.431      0.666      -7.641      11.948
Country_Saudi Arabia                                         1.9985      4.906      0.407      0.684      -7.618      11.615
Country_Singapore                                            1.1401      4.647      0.245      0.806      -7.968      10.248
Country_South Africa                                       -22.5049   6.84e+05  -3.29e-05      1.000   -1.34e+06    1.34e+06
Country_Sri Lanka                                          -25.0288   1.38e+06  -1.82e-05      1.000    -2.7e+06     2.7e+06
Country_Sweden                                             -20.5253   1.45e+06  -1.42e-05      1.000   -2.84e+06    2.84e+06
Country_Tanzania                                         -1.177e-08      0.015  -7.99e-07      1.000      -0.029       0.029
Country_Uganda                                             -23.2707   6.19e+05  -3.76e-05      1.000   -1.21e+06    1.21e+06
Country_United Arab Emirates                                -0.1166      4.486     -0.026      0.979      -8.909       8.676
Country_United Kingdom                                       5.4969      5.823      0.944      0.345      -5.915      16.909
Country_United States                                        0.6818      4.703      0.145      0.885      -8.536       9.900
Country_Vietnam                                            -23.9942   1.06e+06  -2.27e-05      1.000   -2.08e+06    2.08e+06
Lead Profile_Lateral Student                                 7.2129   6.04e+05   1.19e-05      1.000   -1.18e+06    1.18e+06
Lead Profile_Other Leads                                   -25.3358   4.16e+05  -6.09e-05      1.000   -8.16e+05    8.15e+05
Lead Profile_Potential Lead                                -24.9234   4.16e+05  -5.99e-05      1.000   -8.16e+05    8.15e+05
Lead Profile_Select                                        -26.1807   4.16e+05  -6.29e-05      1.000   -8.16e+05    8.15e+05
Lead Profile_Student of SomeSchool                         -26.4883   4.16e+05  -6.37e-05      1.000   -8.16e+05    8.15e+05
How did you hear about X Education_Email                    -0.1315      1.690     -0.078      0.938      -3.443       3.180
How did you hear about X Education_Multiple Sources         -2.1244      1.005     -2.114      0.035      -4.094      -0.154
How did you hear about X Education_Online Search            -0.5945      0.839     -0.709      0.478      -2.238       1.049
How did you hear about X Education_Other                     0.6382      0.955      0.668      0.504      -1.234       2.511
How did you hear about X Education_SMS                       1.5847      1.512      1.048      0.295      -1.380       4.549
How did you hear about X Education_Select                   -1.4172      0.881     -1.610      0.108      -3.143       0.309
How did you hear about X Education_Social Media             -0.5580      1.640     -0.340      0.734      -3.772       2.656
How did you hear about X Education_Student of SomeSchool    -0.4513      0.943     -0.479      0.632      -2.299       1.397
How did you hear about X Education_Word Of Mouth            -1.0680      0.899     -1.189      0.235      -2.829       0.693
Tags_Busy                                                    6.0525      1.425      4.248      0.000       3.260       8.845
Tags_Closed by Horizzon                                     11.6273      1.778      6.539      0.000       8.142      15.113
Tags_Diploma holder (Not Eligible)                           2.1839      1.819      1.201      0.230      -1.380       5.748
Tags_Graduation in progress                                  3.6657      1.490      2.460      0.014       0.745       6.586
Tags_In confusion whether part time or DLP                   5.0642      1.863      2.718      0.007       1.413       8.716
Tags_Interested  in full time MBA                            1.5700      1.736      0.904      0.366      -1.833       4.973
Tags_Interested in Next batch                               33.1652   5.25e+05   6.32e-05      1.000   -1.03e+06    1.03e+06
Tags_Interested in other courses                             2.1114      1.473      1.433      0.152      -0.776       4.998
Tags_Lateral student                                        35.8460   1.84e+06   1.95e-05      1.000   -3.61e+06    3.61e+06
Tags_Lost to EINS                                           10.7351      1.612      6.659      0.000       7.575      13.895
Tags_Lost to Others                                        -25.8652   7.84e+05   -3.3e-05      1.000   -1.54e+06    1.54e+06
Tags_Not doing further education                             1.0764      1.846      0.583      0.560      -2.542       4.694
Tags_Recognition issue (DEC approval)                      -25.5337   1.23e+06  -2.07e-05      1.000   -2.41e+06    2.41e+06
Tags_Ringing                                                 1.9819      1.411      1.404      0.160      -0.784       4.748
Tags_Shall take in the next coming month                   -23.7043   1.69e+06   -1.4e-05      1.000   -3.31e+06    3.31e+06
Tags_Still Thinking                                          3.5610      2.019      1.764      0.078      -0.397       7.519
Tags_University not recognized                             -23.7475   1.76e+06  -1.35e-05      1.000   -3.44e+06    3.44e+06
Tags_Want to take admission but has financial problems       4.1120      2.037      2.019      0.044       0.120       8.104
Tags_Will revert after reading the email                     9.1865      1.419      6.474      0.000       6.405      11.968
Tags_in touch with EINS                                      5.9484      1.692      3.516      0.000       2.632       9.265
Tags_invalid number                                          1.7515      1.783      0.982      0.326      -1.743       5.246
Tags_number not provided                                   -25.7758   3.73e+05  -6.91e-05      1.000   -7.31e+05    7.31e+05
Tags_opp hangup                                              2.3942      1.757      1.363      0.173      -1.049       5.837
Tags_switched off                                            1.1602      1.484      0.782      0.434      -1.748       4.069
Tags_wrong number given                                    -23.9455   2.43e+05  -9.84e-05      1.000   -4.77e+05    4.77e+05
City_Other Cities                                            0.0762      0.359      0.212      0.832      -0.627       0.779
City_Other Cities of Maharashtra                            -0.1318      0.430     -0.306      0.759      -0.975       0.711
City_Other Metro Cities                                     -0.1795      0.549     -0.327      0.744      -1.255       0.896
City_Select                                                  0.4217      0.563      0.749      0.454      -0.682       1.526
City_Thane & Outskirts                                      -0.0897      0.377     -0.238      0.812      -0.828       0.648
City_Tier II Cities                                          0.5517      0.778      0.709      0.478      -0.974       2.077
Last Notable Activity_Email Bounced                          3.1431    2.1e+06    1.5e-06      1.000   -4.11e+06    4.11e+06
Last Notable Activity_Email Link Clicked                    -1.5754    2.1e+06  -7.51e-07      1.000   -4.11e+06    4.11e+06

In [72]:
res.summary2()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                                             Results: Generalized linear model
===========================================================================================================================
Model:                                   GLM                                 AIC:                               991.2682
Link Function:                           Logit                               BIC:                               -23763.2344
Dependent Variable:                      Converted                           Log-Likelihood:                    -357.63
Date:                                    2026-05-23 11:47                    LL-Null:                           -2165.4
No. Observations:                        3174                                Deviance:                          715.27
Df Model:                                137                                 Pearson chi2:                      2.57e+03
Df Residuals:                            3036                                Scale:                             1.0000
Method:                                  IRLS
---------------------------------------------------------------------------------------------------------------------------
                                                          Coef.      Std.Err.      z    P>|z|      [0.025         0.975]
---------------------------------------------------------------------------------------------------------------------------
const                                                     46.3902  1887960.1654  0.0000 1.0000  -3700287.5381  3700380.3186
Do Not Email                                              -0.5955        0.6144 -0.9692 0.3325        -1.7998        0.6088
Do Not Call                                               24.9962   354216.6391  0.0001 0.9999   -694226.8592   694276.8516
TotalVisits                                                0.2398        0.1154  2.0778 0.0377         0.0136        0.4659
Total Time Spent on Website                                1.3167        0.1812  7.2666 0.0000         0.9615        1.6718
Page Views Per Visit                                      -0.1959        0.1687 -1.1615 0.2454        -0.5265        0.1347
Search                                                    -0.9119        3.3943 -0.2687 0.7882        -7.5647        5.7409
Magazine                                                   0.0000        0.0721  0.0000 1.0000        -0.1413        0.1413
Newspaper Article                                         18.7892    11722.1337  0.0016 0.9987    -22956.1707    22993.7492
X Education Forums                                        -0.0000        0.0974 -0.0000 1.0000        -0.1909        0.1909
Newspaper                                                 -0.0000        0.1850 -0.0000 1.0000        -0.3626        0.3626
Digital Advertisement                                    -31.0765 32799329.0398 -0.0000 1.0000 -64285534.7116 64285472.5586
Through Recommendations                                   25.7480   970962.0739  0.0000 1.0000  -1903024.9471  1903076.4432
Receive More Updates About Our Courses                     0.0000        0.0883  0.0000 1.0000        -0.1730        0.1730
Update me on Supply Chain Content                          0.0000        0.3777  0.0000 1.0000        -0.7403        0.7403
Get updates on DM Content                                 -0.0000        0.1946 -0.0000 1.0000        -0.3813        0.3813
I agree to pay the amount through cheque                  -0.0000        0.1807 -0.0000 1.0000        -0.3541        0.3541
A free copy of Mastering The Interview                     0.0113        0.3732  0.0303 0.9758        -0.7201        0.7427
Lead Origin_Landing Page Submission                        0.2818        0.4709  0.5985 0.5495        -0.6411        1.2048
Lead Origin_Lead Add Form                                 18.7974  1270077.1221  0.0000 1.0000  -2489286.6194  2489324.2143
Lead Source_Facebook                                      -0.0000        0.1516 -0.0000 1.0000        -0.2972        0.2972
Lead Source_Google                                         0.1836        0.3483  0.5271 0.5981        -0.4990        0.8662
Lead Source_Olark Chat                                     0.8559        1.2315  0.6950 0.4871        -1.5578        3.2695
Lead Source_Organic Search                                 0.3927        0.3450  1.1385 0.2549        -0.2834        1.0688
Lead Source_Pay per Click Ads                            -25.8259  1895891.2543 -0.0000 1.0000  -3715904.4029  3715852.7511
Lead Source_Press_Release                                 -0.0000        0.3291 -0.0000 1.0000        -0.6451        0.6451
Lead Source_Reference                                      7.4773  1298718.4832  0.0000 1.0000  -2545433.9759  2545448.9305
Lead Source_Referral Sites                                 1.5303        0.9029  1.6948 0.0901        -0.2395        3.3000
Lead Source_Social Media                                   1.9779        7.1575  0.2763 0.7823       -12.0505       16.0063
Lead Source_WeLearn                                       -0.0000        0.0946 -0.0000 1.0000        -0.1854        0.1854
Lead Source_Welingak Website                              11.3201  2525630.5703  0.0000 1.0000  -4950133.6360  4950156.2762
Lead Source_bing                                         -24.0738  3025331.0654 -0.0000 1.0000  -5929564.0034  5929515.8557
Lead Source_testone                                       -0.0000        0.2076 -0.0000 1.0000        -0.4069        0.4069
Specialization_Business Administration                    -0.2599        0.6487 -0.4006 0.6887        -1.5313        1.0116
Specialization_E-Business                                 -1.5243        1.1910 -1.2798 0.2006        -3.8586        0.8101
Specialization_E-COMMERCE                                 -0.0514        0.9377 -0.0548 0.9563        -1.8894        1.7865
Specialization_Finance Management                         -0.7495        0.5676 -1.3205 0.1867        -1.8619        0.3630
Specialization_Healthcare Management                       1.2822        0.9284  1.3811 0.1673        -0.5374        3.1019
Specialization_Hospitality Management                     -1.4648        0.8549 -1.7133 0.0867        -3.1405        0.2109
Specialization_Human Resource Management                  -0.5725        0.5758 -0.9942 0.3201        -1.7010        0.5561
Specialization_IT Projects Management                     -0.0848        0.6775 -0.1252 0.9003        -1.4126        1.2430
Specialization_International Business                     -0.3133        0.8006 -0.3913 0.6956        -1.8823        1.2558
Specialization_Marketing Management                       -0.2542        0.5683 -0.4473 0.6547        -1.3681        0.8597
Specialization_Media and Advertising                      -0.5408        0.8113 -0.6666 0.5050        -2.1310        1.0493
Specialization_Operations Management                      -0.0728        0.6154 -0.1182 0.9059        -1.2790        1.1335
Specialization_Retail Management                          -0.5187        1.0530 -0.4925 0.6223        -2.5825        1.5452
Specialization_Rural and Agribusiness                      0.7429        1.0140  0.7327 0.4638        -1.2444        2.7302
Specialization_Select                                     -0.5798        0.7247 -0.8000 0.4237        -2.0001        0.8406
Specialization_Services Excellence                        -0.8714        1.3265 -0.6569 0.5112        -3.4714        1.7285
Specialization_Supply Chain Management                    -1.4211        0.6615 -2.1482 0.0317        -2.7177       -0.1246
Specialization_Travel and Tourism                         -1.0810        0.7865 -1.3743 0.1693        -2.6226        0.4606
What is your current occupation_Housewife                 24.4379   786906.4317  0.0000 1.0000  -1542283.8274  1542332.7032
What is your current occupation_Other                     -0.1889        5.8163 -0.0325 0.9741       -11.5887       11.2109
What is your current occupation_Student                    0.6768        5.6835  0.1191 0.9052       -10.4625       11.8162
What is your current occupation_Unemployed                -0.3700        5.6068 -0.0660 0.9474       -11.3591       10.6190
What is your current occupation_Working Professional       0.2377        5.6195  0.0423 0.9663       -10.7764       11.2518
What matters most to you in choosing a course_Other      -23.8737   793705.0099 -0.0000 1.0000  -1555657.1074  1555609.3599
Last Activity_Converted to Lead                          -24.3811  1006456.8453 -0.0000 1.0000  -1972643.5499  1972594.7876
Last Activity_Email Bounced                              -26.4588  1006456.8453 -0.0000 1.0000  -1972645.6276  1972592.7099
Last Activity_Email Link Clicked                         -23.0099  1006456.8453 -0.0000 1.0000  -1972642.1787  1972596.1588
Last Activity_Email Marked Spam                           -2.4796  1000385.3979 -0.0000 1.0000  -1960721.8301  1960716.8710
Last Activity_Email Opened                               -24.3634  1006456.8453 -0.0000 1.0000  -1972643.5321  1972594.8054
Last Activity_Email Received                              -1.1073   970604.5532 -0.0000 1.0000  -1902351.0748  1902348.8602
Last Activity_Form Submitted on Website                  -23.4961  1006456.8453 -0.0000 1.0000  -1972642.6649  1972595.6726
Last Activity_Had a Phone Conversation                   -25.5999  1006456.8453 -0.0000 1.0000  -1972644.7686  1972593.5689
Last Activity_Olark Chat Conversation                    -23.0186  1006456.8453 -0.0000 1.0000  -1972642.1874  1972596.1501
Last Activity_Page Visited on Website                    -24.1759  1006456.8453 -0.0000 1.0000  -1972643.3447  1972594.9928
Last Activity_SMS Sent                                   -22.4259  1006456.8453 -0.0000 1.0000  -1972641.5946  1972596.7429
Last Activity_Unreachable                                -23.8252  1006456.8453 -0.0000 1.0000  -1972642.9939  1972595.3436
Last Activity_Unsubscribed                               -23.6677  1006456.8453 -0.0000 1.0000  -1972642.8364  1972595.5011
Last Activity_View in browser link Clicked               -23.0854  1076581.8697 -0.0000 1.0000  -2110084.7763  2110038.6055
Last Activity_Visited Booth in Tradeshow                  -0.0000        0.0211 -0.0000 1.0000        -0.0414        0.0414
Country_Bahrain                                            1.6923        7.5479  0.2242 0.8226       -13.1013       16.4859
Country_Bangladesh                                        27.5725  3522301.8814  0.0000 1.0000  -6903557.2577  6903612.4026
Country_Canada                                           -23.1016   572324.8887 -0.0000 1.0000  -1121759.2708  1121713.0676
Country_China                                             -0.0000        0.0072 -0.0000 1.0000        -0.0141        0.0141
Country_Denmark                                            0.0000        0.0025  0.0000 1.0000        -0.0049        0.0049
Country_France                                            23.2646   415775.9388  0.0001 1.0000   -814882.6011   814929.1303
Country_Germany                                            7.0599        4.6901  1.5053 0.1322        -2.1324       16.2522
Country_Ghana                                            -21.2300  1302195.6658 -0.0000 1.0000  -2552277.8357  2552235.3757
Country_Hong Kong                                          5.0752        4.6486  1.0918 0.2749        -4.0360       14.1863
Country_India                                              0.9016        4.3698  0.2063 0.8365        -7.6631        9.4662
Country_Indonesia                                          0.0000        0.0285  0.0000 1.0000        -0.0558        0.0558
Country_Italy                                             -0.0000        0.0348 -0.0000 1.0000        -0.0682        0.0682
Country_Kenya                                              0.0000        0.0082  0.0000 1.0000        -0.0160        0.0160
Country_Kuwait                                           -21.9636   766990.8162 -0.0000 1.0000  -1503296.3397  1503252.4125
Country_Malaysia                                           0.0000        0.0341  0.0000 1.0000        -0.0667        0.0667
Country_Netherlands                                      -26.3165  1302760.7128 -0.0000 1.0000  -2553390.3940  2553337.7611
Country_Nigeria                                          -22.8891   870119.4454 -0.0000 1.0000  -1705425.6642  1705379.8861
Country_Oman                                               2.0830        5.7525  0.3621 0.7173        -9.1916       13.3576
Country_Philippines                                      -23.2574  1301015.4051 -0.0000 1.0000  -2549966.5948  2549920.0800
Country_Qatar                                              2.1536        4.9972  0.4310 0.6665        -7.6407       11.9479
Country_Saudi Arabia                                       1.9985        4.9063  0.4073 0.6838        -7.6176       11.6146
Country_Singapore                                          1.1401        4.6472  0.2453 0.8062        -7.9683       10.2485
Country_South Africa                                     -22.5049   683866.4252 -0.0000 1.0000  -1340376.0685  1340331.0586
Country_Sri Lanka                                        -25.0288  1375229.0306 -0.0000 1.0000  -2695424.3991  2695374.3416
Country_Sweden                                           -20.5253  1447905.8998 -0.0000 1.0000  -2837863.9419  2837822.8913
Country_Tanzania                                          -0.0000        0.0147 -0.0000 1.0000        -0.0289        0.0289
Country_Uganda                                           -23.2707   619439.9234 -0.0000 1.0000  -1214103.2111  1214056.6697
Country_United Arab Emirates                              -0.1166        4.4860 -0.0260 0.9793        -8.9089        8.6757
Country_United Kingdom                                     5.4969        5.8227  0.9440 0.3451        -5.9154       16.9093
Country_United States                                      0.6818        4.7030  0.1450 0.8847        -8.5360        9.8996
Country_Vietnam                                          -23.9942  1059332.1443 -0.0000 1.0000  -2076276.8447  2076228.8562
Lead Profile_Lateral Student                               7.2129   603747.2470  0.0000 1.0000  -1183315.6470  1183330.0729
Lead Profile_Other Leads                                 -25.3358   416087.4982 -0.0001 1.0000   -815541.8467   815491.1750
Lead Profile_Potential Lead                              -24.9234   416087.4982 -0.0001 1.0000   -815541.4343   815491.5874
Lead Profile_Select                                      -26.1807   416087.4982 -0.0001 0.9999   -815542.6915   815490.3301
Lead Profile_Student of SomeSchool                       -26.4883   416087.4982 -0.0001 0.9999   -815542.9991   815490.0226
How did you hear about X Education_Email                  -0.1315        1.6897 -0.0778 0.9380        -3.4433        3.1803
How did you hear about X Education_Multiple Sources       -2.1244        1.0051 -2.1137 0.0345        -4.0943       -0.1545
How did you hear about X Education_Online Search          -0.5945        0.8387 -0.7088 0.4784        -2.2384        1.0494
How did you hear about X Education_Other                   0.6382        0.9554  0.6680 0.5041        -1.2344        2.5108
How did you hear about X Education_SMS                     1.5847        1.5125  1.0477 0.2948        -1.3798        4.5491
How did you hear about X Education_Select                 -1.4172        0.8805 -1.6095 0.1075        -3.1430        0.3086
How did you hear about X Education_Social Media           -0.5580        1.6397 -0.3403 0.7336        -3.7718        2.6558
How did you hear about X Education_Student of SomeSchool  -0.4513        0.9429 -0.4786 0.6322        -2.2994        1.3968
How did you hear about X Education_Word Of Mouth          -1.0680        0.8986 -1.1885 0.2346        -2.8293        0.6933
Tags_Busy                                                  6.0525        1.4248  4.2481 0.0000         3.2600        8.8449
Tags_Closed by Horizzon                                   11.6273        1.7782  6.5386 0.0000         8.1420       15.1126
Tags_Diploma holder (Not Eligible)                         2.1839        1.8186  1.2009 0.2298        -1.3804        5.7482
Tags_Graduation in progress                                3.6657        1.4900  2.4603 0.0139         0.7454        6.5860
Tags_In confusion whether part time or DLP                 5.0642        1.8631  2.7182 0.0066         1.4126        8.7157
Tags_Interested  in full time MBA                          1.5700        1.7365  0.9041 0.3659        -1.8334        4.9734
Tags_Interested in Next batch                             33.1652   524608.2933  0.0001 0.9999  -1028180.1956  1028246.5260
Tags_Interested in other courses                           2.1114        1.4730  1.4334 0.1517        -0.7756        4.9984
Tags_Lateral student                                      35.8460  1841538.6989  0.0000 1.0000  -3609313.6800  3609385.3721
Tags_Lost to EINS                                         10.7351        1.6121  6.6589 0.0000         7.5754       13.8949
Tags_Lost to Others                                      -25.8652   784394.9782 -0.0000 1.0000  -1537411.7721  1537360.0417
Tags_Not doing further education                           1.0764        1.8460  0.5831 0.5598        -2.5418        4.6945
Tags_Recognition issue (DEC approval)                    -25.5337  1231843.2895 -0.0000 1.0000  -2414394.0157  2414342.9483
Tags_Ringing                                               1.9819        1.4114  1.4043 0.1602        -0.7843        4.7482
Tags_Shall take in the next coming month                 -23.7043  1687829.7206 -0.0000 1.0000  -3308109.1688  3308061.7601
Tags_Still Thinking                                        3.5610        2.0192  1.7636 0.0778        -0.3966        7.5186
Tags_University not recognized                           -23.7475  1756977.8463 -0.0000 1.0000  -3443637.0478  3443589.5528
Tags_Want to take admission but has financial problems     4.1120        2.0368  2.0188 0.0435         0.1199        8.1040
Tags_Will revert after reading the email                   9.1865        1.4189  6.4742 0.0000         6.4054       11.9675
Tags_in touch with EINS                                    5.9484        1.6920  3.5156 0.0004         2.6322        9.2647
Tags_invalid number                                        1.7515        1.7828  0.9825 0.3259        -1.7427        5.2457
Tags_number not provided                                 -25.7758   373132.1283 -0.0001 0.9999   -731351.3087   731299.7571
Tags_opp hangup                                            2.3942        1.7567  1.3629 0.1729        -1.0488        5.8372
Tags_switched off                                          1.1602        1.4840  0.7818 0.4343        -1.7483        4.0687
Tags_wrong number given                                  -23.9455   243408.3912 -0.0001 0.9999   -477095.6257   477047.7347
City_Other Cities                                          0.0762        0.3587  0.2125 0.8317        -0.6269        0.7793
City_Other Cities of Maharashtra                          -0.1318        0.4301 -0.3064 0.7593        -0.9748        0.7112
City_Other Metro Cities                                   -0.1795        0.5487 -0.3271 0.7436        -1.2550        0.8960
City_Select                                                0.4217        0.5634  0.7485 0.4541        -0.6825        1.5259
City_Thane & Outskirts                                    -0.0897        0.3765 -0.2381 0.8118        -0.8277        0.6484
City_Tier II Cities                                        0.5517        0.7782  0.7090 0.4783        -0.9735        2.0770
Last Notable Activity_Email Bounced                        3.1431  2098623.3966  0.0000 1.0000  -4113223.1313  4113229.4176

In [73]:
res.pvalues.sort_values(ascending=False).head(10)

Country_China                                    1.000000
Country_Italy                                    1.000000
Last Activity_Visited Booth in Tradeshow         0.999999
Last Notable Activity_Email Link Clicked         0.999999
Country_Kenya                                    0.999999
Country_Tanzania                                 0.999999
Lead Source_testone                              0.999999
Newspaper                                        0.999999
Last Notable Activity_Page Visited on Website    0.999999
Lead Source_Facebook                             0.999999
dtype: float64

In [74]:
col = ['Country_China',
       'Country_Italy',
       'Last Activity_Visited Booth in Tradeshow',
       'Last Notable Activity_Email Link Clicked',
       'Country_Kenya',
       'Country_Tanzania',
       'Lead Source_testone',
       'Newspaper',
       'Last Notable Activity_Page Visited on Website',
       'Lead Source_Facebook']

X_train = X_train.drop(col, axis=1)

In [75]:
logm1 = sm.GLM(y_train, sm.add_constant(X_train), family=sm.families.Binomial())
res = logm1.fit()
res.summary2()

C:\Users\Dell\anaconda3\Lib\site-packages\statsmodels\genmod\families\links.py:198: RuntimeWarning: overflow encountered in exp
  t = np.exp(-z)

MemoryError:

In [1]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [5]:
leads.shape

(9240, 37)

In [6]:
leads = leads.drop(['Prospect ID','Lead Number'], axis=1)

In [7]:
leads.shape

(9240, 35)

In [8]:
leads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 35 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Lead Origin                                    9240 non-null   object
 1   Lead Source                                    9204 non-null   object
 2   Do Not Email                                   9240 non-null   object
 3   Do Not Call                                    9240 non-null   object
 4   Converted                                      9240 non-null   int64
 5   TotalVisits                                    9103 non-null   float64
 6   Total Time Spent on Website                    9240 non-null   int64
 7   Page Views Per Visit                           9103 non-null   float64
 8   Last Activity                                  9137 non-null   object
 9   Country                                        6779 non-null   object
 10  Specialization                                 7802 non-null   object
 11  How did you hear about X Education             7033 non-null   object
 12  What is your current occupation                6550 non-null   object
 13  What matters most to you in choosing a course  6531 non-null   object
 14  Search                                         9240 non-null   object
 15  Magazine                                       9240 non-null   object
 16  Newspaper Article                              9240 non-null   object
 17  X Education Forums                             9240 non-null   object
 18  Newspaper                                      9240 non-null   object
 19  Digital Advertisement                          9240 non-null   object
 20  Through Recommendations                        9240 non-null   object
 21  Receive More Updates About Our Courses         9240 non-null   object
 22  Tags                                           5887 non-null   object
 23  Lead Quality                                   4473 non-null   object
 24  Update me on Supply Chain Content              9240 non-null   object
 25  Get updates on DM Content                      9240 non-null   object
 26  Lead Profile                                   6531 non-null   object
 27  City                                           7820 non-null   object
 28  Asymmetrique Activity Index                    5022 non-null   object
 29  Asymmetrique Profile Index                     5022 non-null   object
 30  Asymmetrique Activity Score                    5022 non-null   float64
 31  Asymmetrique Profile Score                     5022 non-null   float64
 32  I agree to pay the amount through cheque       9240 non-null   object
 33  A free copy of Mastering The Interview         9240 non-null   object
 34  Last Notable Activity                          9240 non-null   object
dtypes: float64(4), int64(2), object(29)
memory usage: 2.5+ MB

In [9]:
round(100*(leads.isnull().sum()/len(leads.index)),2).sort_values(ascending=False)

Lead Quality                                     51.59
Asymmetrique Activity Index                      45.65
Asymmetrique Activity Score                      45.65
Asymmetrique Profile Score                       45.65
Asymmetrique Profile Index                       45.65
Tags                                             36.29
What matters most to you in choosing a course    29.32
Lead Profile                                     29.32
What is your current occupation                  29.11
Country                                          26.63
How did you hear about X Education               23.89
Specialization                                   15.56
City                                             15.37
Page Views Per Visit                              1.48
TotalVisits                                       1.48
Last Activity                                     1.11
Lead Source                                       0.39
Do Not Email                                      0.00
Lead Origin                                       0.00
Newspaper                                         0.00
X Education Forums                                0.00
Newspaper Article                                 0.00
Magazine                                          0.00
Search                                            0.00
Total Time Spent on Website                       0.00
Do Not Call                                       0.00
Converted                                         0.00
Get updates on DM Content                         0.00
Update me on Supply Chain Content                 0.00
Through Recommendations                           0.00
Receive More Updates About Our Courses            0.00
Digital Advertisement                             0.00
I agree to pay the amount through cheque          0.00
A free copy of Mastering The Interview            0.00
Last Notable Activity                             0.00
dtype: float64

In [10]:
cols = ['Lead Quality',
        'Asymmetrique Activity Index',
        'Asymmetrique Activity Score',
        'Asymmetrique Profile Index',
        'Asymmetrique Profile Score',
        'Tags']

leads = leads.drop(cols, axis=1)

In [11]:
leads.shape

(9240, 29)

In [13]:
leads = leads.dropna()

In [14]:
leads.shape

(4925, 29)

In [15]:
round(100*(leads.isnull().sum()/len(leads.index)),2).sort_values(ascending=False)

Lead Origin                                      0.0
Lead Source                                      0.0
Do Not Email                                     0.0
Do Not Call                                      0.0
Converted                                        0.0
TotalVisits                                      0.0
Total Time Spent on Website                      0.0
Page Views Per Visit                             0.0
Last Activity                                    0.0
Country                                          0.0
Specialization                                   0.0
How did you hear about X Education               0.0
What is your current occupation                  0.0
What matters most to you in choosing a course    0.0
Search                                           0.0
Magazine                                         0.0
Newspaper Article                                0.0
X Education Forums                               0.0
Newspaper                                        0.0
Digital Advertisement                            0.0
Through Recommendations                          0.0
Receive More Updates About Our Courses           0.0
Update me on Supply Chain Content                0.0
Get updates on DM Content                        0.0
Lead Profile                                     0.0
City                                             0.0
I agree to pay the amount through cheque         0.0
A free copy of Mastering The Interview           0.0
Last Notable Activity                            0.0
dtype: float64

In [16]:
leads.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4925 entries, 1 to 9239
Data columns (total 29 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Lead Origin                                    4925 non-null   object
 1   Lead Source                                    4925 non-null   object
 2   Do Not Email                                   4925 non-null   object
 3   Do Not Call                                    4925 non-null   object
 4   Converted                                      4925 non-null   int64
 5   TotalVisits                                    4925 non-null   float64
 6   Total Time Spent on Website                    4925 non-null   int64
 7   Page Views Per Visit                           4925 non-null   float64
 8   Last Activity                                  4925 non-null   object
 9   Country                                        4925 non-null   object
 10  Specialization                                 4925 non-null   object
 11  How did you hear about X Education             4925 non-null   object
 12  What is your current occupation                4925 non-null   object
 13  What matters most to you in choosing a course  4925 non-null   object
 14  Search                                         4925 non-null   object
 15  Magazine                                       4925 non-null   object
 16  Newspaper Article                              4925 non-null   object
 17  X Education Forums                             4925 non-null   object
 18  Newspaper                                      4925 non-null   object
 19  Digital Advertisement                          4925 non-null   object
 20  Through Recommendations                        4925 non-null   object
 21  Receive More Updates About Our Courses         4925 non-null   object
 22  Update me on Supply Chain Content              4925 non-null   object
 23  Get updates on DM Content                      4925 non-null   object
 24  Lead Profile                                   4925 non-null   object
 25  City                                           4925 non-null   object
 26  I agree to pay the amount through cheque       4925 non-null   object
 27  A free copy of Mastering The Interview         4925 non-null   object
 28  Last Notable Activity                          4925 non-null   object
dtypes: float64(2), int64(2), object(25)
memory usage: 1.1+ MB

In [17]:
varlist = ['Lead Origin',
           'Lead Source',
           'Do Not Email',
           'Do Not Call',
           'Last Activity',
           'Country',
           'Specialization',
           'How did you hear about X Education',
           'What is your current occupation',
           'What matters most to you in choosing a course',
           'Search',
           'Magazine',
           'Newspaper Article',
           'X Education Forums',
           'Newspaper',
           'Digital Advertisement',
           'Through Recommendations',
           'Receive More Updates About Our Courses',
           'Update me on Supply Chain Content',
           'Get updates on DM Content',
           'Lead Profile',
           'City',
           'I agree to pay the amount through cheque',
           'A free copy of Mastering The Interview',
           'Last Notable Activity']

In [18]:
dummy = pd.get_dummies(leads[varlist], drop_first=True)

In [19]:
leads = pd.concat([leads, dummy], axis=1)

In [20]:
leads = leads.drop(varlist, axis=1)

In [21]:
leads.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4925 entries, 1 to 9239
Columns: 132 entries, Converted to Last Notable Activity_View in browser link Clicked
dtypes: bool(128), float64(2), int64(2)
memory usage: 808.0 KB

In [22]:
X = leads.drop('Converted', axis=1)
y = leads['Converted']

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=100
)

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()

In [27]:
X_train[['TotalVisits','Total Time Spent on Website','Page Views Per Visit']] = scaler.fit_transform(
    X_train[['TotalVisits','Total Time Spent on Website','Page Views Per Visit']]
)

In [28]:
X_train[['TotalVisits','Total Time Spent on Website','Page Views Per Visit']] = scaler.fit_transform(
    X_train[['TotalVisits','Total Time Spent on Website','Page Views Per Visit']]
)

In [32]:
logreg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [33]:
y_pred = logreg.predict(X_test)

In [34]:
from sklearn.metrics import accuracy_score

In [35]:
accuracy_score(y_test, y_pred)

0.4506089309878214

In [36]:
from sklearn.metrics import classification_report

In [37]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.00      0.00       813
           1       0.45      1.00      0.62       665

    accuracy                           0.45      1478
   macro avg       0.73      0.50      0.31      1478
weighted avg       0.75      0.45      0.28      1478

In [38]:
logreg = LogisticRegression(max_iter=1000, class_weight='balanced')

In [39]:
logreg.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [40]:
y_pred = logreg.predict(X_test)

In [41]:
accuracy_score(y_test, y_pred)

0.44993234100135315

In [42]:
from sklearn.metrics import confusion_matrix

In [43]:
confusion_matrix(y_test, y_pred)

array([[  0, 813],
       [  0, 665]])

Conclusion:
The Logistic Regression model was successfully implemented on the Leads dataset.
Data preprocessing techniques such as handling missing values, encoding categorical variables, scaling and train-test splitting were performed sucessfully.
The model achieved an accuracy of approximately 45% on the test data.
Model evaluation was carried out using accuracy score, classification report, and confusion matrix.